/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HttpsLbCliDevConfigSchemaJson {
  /**
   * Default Linear team key (e.g., 'LIN'). Used when no team is specified in commands.
   */
  team_key?: string;
  /**
   * Name used for repo: label in Linear. Overrides auto-detection from git remote or directory name.
   */
  repo_name?: string;
  /**
   * Name of the Linear project for scoping issues. Overrides auto-detection from repo_name or git remote/directory name.
   */
  project_name?: string;
  /**
   * Linear project ID (UUID). If set, skips project lookup by name.
   */
  project_id?: string;
  /**
   * Enable issue type labels (Bug, Feature, Task, etc.) using Linear label groups. When false, types are not tracked.
   */
  use_issue_types?: boolean;
  /**
   * How long to trust cached data before re-syncing from Linear, in seconds.
   */
  cache_ttl_seconds?: number;
  /**
   * Run in local-only mode without syncing to Linear. Issues get LOCAL-xxx IDs. Useful for LLM-only task tracking.
   */
  local_only?: boolean;
  /**
   * Automatically assign new issues to the current user. When false (default), issues are created without an assignee unless --assign is used.
   */
  auto_assign?: boolean;
}
